apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: starting-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: app-service-account  # Add this line
      containers:
        - name: app
          image:  ghcr.io/marpusiddardha/startingdocker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-credentials
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"