apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: starting-docker
type: Opaque
data:
  # echo -n 'postgres' | base64
  username: cG9zdGdyZXM=
  # echo -n 'postgres' | base64
  password: cG9zdGdyZXM=
